/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NewsletterSignup = {
  _id: string;
  _type: "newsletterSignup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  signedUpAt: string;
};

export type SearchQuery = {
  _id: string;
  _type: "searchQuery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  query: string;
  count?: number;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber: string;
  items?: Array<{
    product: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity: number;
    priceAtPurchase: number;
    _key: string;
  }>;
  total?: number;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  clerkUserId?: string;
  email?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  stripePaymentId?: string;
  createdAt?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  price: number;
  salePrice?: number;
  category: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  material?: "wood" | "metal" | "fabric" | "leather" | "glass";
  color?: "black" | "white" | "oak" | "walnut" | "grey" | "natural";
  productType?: string;
  variantGroup?: string;
  dimensions?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  featured?: boolean;
  isNew?: boolean;
  assemblyRequired?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  name?: string;
  clerkUserId?: string;
  stripeCustomerId: string;
  createdAt?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | NewsletterSignup
  | SearchQuery
  | Order
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Customer
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: lib/sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[  _type == "category"] | order(title asc) {  _id,  title,  "slug": slug.current,  "image": *[_type == "product" && category._ref == ^._id && defined(images[0])][0].images[0]{    asset->{      _id,      url    }  }}
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[  _type == "category"  && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: lib/sanity/queries/customers.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[  _type == "customer"  && email == $email][0]{  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_EMAIL_QUERY_RESULT = {
  _id: string;
  email: string;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string;
  createdAt: string | null;
} | null;

// Source: lib/sanity/queries/customers.ts
// Variable: CUSTOMER_BY_STRIPE_ID_QUERY
// Query: *[  _type == "customer"  && stripeCustomerId == $stripeCustomerId][0]{  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_STRIPE_ID_QUERY_RESULT = {
  _id: string;
  email: string;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string;
  createdAt: string | null;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  "itemNames": items[].product->name,  "itemImages": items[].product->images[0].asset->url}
export type ORDERS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string> | null;
  itemImages: Array<string | null> | null;
}>;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  email,  items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      name,      "slug": slug.current,      "image": images[0]{        asset->{          _id,          url        }      }    }  },  total,  status,  address{    name,    line1,    line2,    city,    postcode,    country  },  stripePaymentId,  createdAt}
export type ORDER_BY_ID_QUERY_RESULT = {
  _id: string;
  orderNumber: string;
  clerkUserId: string | null;
  email: string | null;
  items: Array<{
    _key: string;
    quantity: number;
    priceAtPurchase: number;
    product: {
      _id: string;
      name: string;
      slug: string;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    };
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  address: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    postcode: string | null;
    country: string | null;
  } | null;
  stripePaymentId: string | null;
  createdAt: string | null;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: RECENT_ORDERS_QUERY
// Query: *[  _type == "order"] | order(createdAt desc) [0...$limit] {  _id,  orderNumber,  email,  total,  status,  createdAt}
export type RECENT_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string;
  email: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
}>;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_BY_STRIPE_PAYMENT_ID_QUERY
// Query: *[  _type == "order"  && stripePaymentId == $stripePaymentId][0]{ _id }
export type ORDER_BY_STRIPE_PAYMENT_ID_QUERY_RESULT = {
  _id: string;
} | null;

// Source: lib/sanity/queries/products.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[  _type == "product"] | order(name asc) {  _id,  name,  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[  _type == "product"  && featured == true  && stock > 0] | order(name asc) [0...6] {  _id,  name,  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  stock}
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: GALLERY_PRODUCTS_QUERY
// Query: *[  _type == "product"  && defined(images)  && count(images) > 0  && stock > 0] | order(_createdAt desc) [0...14] {  _id,  name,  "slug": slug.current,  "image": images[0]{    asset->{      _id,      url    }  }}
export type GALLERY_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: BEST_SELLERS_QUERY
// Query: *[  _type == "product"  && stock > 0] | order(stock asc, name asc) [0...8] {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type BEST_SELLERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[  _type == "product"  && category->slug.current == $categorySlug] | order(name asc) {  _id,  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[  _type == "product"  && slug.current == $slug][0] {  _id,  name,  "slug": slug.current,  description,  price,  salePrice,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  variantGroup,  dimensions,  stock,  featured,  assemblyRequired}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  variantGroup: string | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
} | null;

// Source: lib/sanity/queries/products.ts
// Variable: VARIANT_SIBLINGS_QUERY
// Query: *[  _type == "product"  && variantGroup == $variantGroup  && defined(variantGroup)  && variantGroup != ""] | order(name asc) {  _id,  "slug": slug.current,  color,  "image": images[0]{    asset->{      url    }  }}
export type VARIANT_SIBLINGS_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: VARIANT_SIBLINGS_FULL_QUERY
// Query: *[  _type == "product"  && variantGroup == $variantGroup  && defined(variantGroup)  && variantGroup != ""] | order(name asc) {  _id,  name,  "slug": slug.current,  description,  price,  salePrice,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type VARIANT_SIBLINGS_FULL_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (    name match $searchQuery + "*"    || description match $searchQuery + "*"  )] | score(  boost(name match $searchQuery + "*", 3),  boost(description match $searchQuery + "*", 1)) | order(_score desc) {  _id,  _score,  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _score: null;
  name: string;
  slug: string;
  price: number;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(name asc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_NAME_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_NAME_DESC_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(name desc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_NAME_DESC_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_NEWEST_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(_createdAt desc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_NEWEST_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(price asc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(price desc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_BEST_SELLING_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(stock asc, name asc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_BEST_SELLING_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[  _type == "product"  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)  && (count($productTypes) == 0 || productType in $productTypes)  && (count($colors) == 0 || color in $colors)  && (count($materials) == 0 || material in $materials)  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")  && ($inStock == false || stock > 0)] | score(  boost(name match $searchQuery + "*", 3),  boost(description match $searchQuery + "*", 1)) | order(_score desc, name asc) {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[  _type == "product"  && _id in $ids] {  _id,  name,  "slug": slug.current,  price,  salePrice,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  stock}
export type PRODUCTS_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCTS_BY_IDS_FULL_QUERY
// Query: *[_type == "product" && _id in $ids] {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type PRODUCTS_BY_IDS_FULL_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: POPULAR_PRODUCTS_QUERY
// Query: *[_type == "product" && stock > 0 && defined(images) && count(images) > 0] | order(featured desc, stock asc, _createdAt desc) [0...8] {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type POPULAR_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: LOW_STOCK_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock > 0  && stock <= 5] | order(stock asc) {  _id,  name,  "slug": slug.current,  stock,  "image": images[0]{    asset->{      _id,      url    }  }}
export type LOW_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  stock: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[  _type == "product"  && category->slug.current == $categorySlug  && slug.current != $currentSlug  && stock > 0] | order(name asc) [0...4] {  _id,  name,  "slug": slug.current,  price,  salePrice,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  stock,  isNew,  variantGroup}
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  salePrice: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
  isNew: boolean | null;
  variantGroup: string | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: OUT_OF_STOCK_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock == 0] | order(name asc) {  _id,  name,  "slug": slug.current,  "image": images[0]{    asset->{      _id,      url    }  }}
export type OUT_OF_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: AI_SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || category->title match $searchQuery + "*"  )  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($material == "" || material == $material)  && ($color == "" || color == $color)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)] | order(name asc) [0...20] {  _id,  name,  "slug": slug.current,  description,  price,  "image": images[0]{    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type AI_SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: lib/sanity/queries/searchQueries.ts
// Variable: POPULAR_SEARCHES_QUERY
// Query: *[  _type == "searchQuery"] | order(count desc) [0...8] {  _id,  query,  count}
export type POPULAR_SEARCHES_QUERY_RESULT = Array<{
  _id: string;
  query: string;
  count: number | null;
}>;

// Source: lib/sanity/queries/searchQueries.ts
// Variable: SEARCH_QUERY_BY_TEXT_QUERY
// Query: *[  _type == "searchQuery"  && query == $searchText][0] {  _id,  query,  count}
export type SEARCH_QUERY_BY_TEXT_QUERY_RESULT = {
  _id: string;
  query: string;
  count: number | null;
} | null;

// Source: lib/sanity/queries/stats.ts
// Variable: PRODUCT_COUNT_QUERY
// Query: count(*[_type == "product"])
export type PRODUCT_COUNT_QUERY_RESULT = number;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDER_COUNT_QUERY
// Query: count(*[_type == "order"])
export type ORDER_COUNT_QUERY_RESULT = number;

// Source: lib/sanity/queries/stats.ts
// Variable: TOTAL_REVENUE_QUERY
// Query: math::sum(*[  _type == "order"  && status in ["paid", "shipped", "delivered"]].total)
export type TOTAL_REVENUE_QUERY_RESULT = number;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDERS_LAST_7_DAYS_QUERY
// Query: *[  _type == "order"  && createdAt >= $startDate  && !(_id in path("drafts.**"))] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  items[]{    quantity,    priceAtPurchase,    "productName": product->name,    "productId": product->_id  }}
export type ORDERS_LAST_7_DAYS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  items: Array<{
    quantity: number;
    priceAtPurchase: number;
    productName: string;
    productId: string;
  }> | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDER_STATUS_DISTRIBUTION_QUERY
// Query: {  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])}
export type ORDER_STATUS_DISTRIBUTION_QUERY_RESULT = {
  paid: number;
  shipped: number;
  delivered: number;
  cancelled: number;
};

// Source: lib/sanity/queries/stats.ts
// Variable: TOP_SELLING_PRODUCTS_QUERY
// Query: *[  _type == "order"  && status in ["paid", "shipped", "delivered"]  && !(_id in path("drafts.**"))] {  items[]{    "productId": product->_id,    "productName": product->name,    "productPrice": product->price,    quantity  }}.items[]
export type TOP_SELLING_PRODUCTS_QUERY_RESULT = Array<{
  productId: string;
  productName: string;
  productPrice: number;
  quantity: number;
} | null>;

// Source: lib/sanity/queries/stats.ts
// Variable: PRODUCTS_INVENTORY_QUERY
// Query: *[_type == "product"] {  _id,  name,  price,  stock,  "category": category->title}
export type PRODUCTS_INVENTORY_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  price: number;
  stock: number | null;
  category: string;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: UNFULFILLED_ORDERS_QUERY
// Query: *[  _type == "order"  && status == "paid"  && !(_id in path("drafts.**"))] | order(createdAt asc) {  _id,  orderNumber,  total,  createdAt,  email,  "itemCount": count(items)}
export type UNFULFILLED_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string;
  total: number | null;
  createdAt: string | null;
  email: string | null;
  itemCount: number | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: REVENUE_BY_PERIOD_QUERY
// Query: {  "currentPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ].total),  "previousPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ].total),  "currentOrderCount": count(*[    _type == "order"    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]),  "previousOrderCount": count(*[    _type == "order"    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ])}
export type REVENUE_BY_PERIOD_QUERY_RESULT = {
  currentPeriod: number;
  previousPeriod: number;
  currentOrderCount: number;
  previousOrderCount: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "category"\n] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  "image": *[_type == "product" && category._ref == ^._id && defined(images[0])][0].images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': ALL_CATEGORIES_QUERY_RESULT;
    '*[\n  _type == "category"\n  && slug.current == $slug\n][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  "image": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "customer"\n  && email == $email\n][0]{\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}': CUSTOMER_BY_EMAIL_QUERY_RESULT;
    '*[\n  _type == "customer"\n  && stripeCustomerId == $stripeCustomerId\n][0]{\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}': CUSTOMER_BY_STRIPE_ID_QUERY_RESULT;
    '*[\n  _type == "order"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  "itemCount": count(items),\n  "itemNames": items[].product->name,\n  "itemImages": items[].product->images[0].asset->url\n}': ORDERS_BY_USER_QUERY_RESULT;
    '*[\n  _type == "order"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  email,\n  items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      name,\n      "slug": slug.current,\n      "image": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  },\n  total,\n  status,\n  address{\n    name,\n    line1,\n    line2,\n    city,\n    postcode,\n    country\n  },\n  stripePaymentId,\n  createdAt\n}': ORDER_BY_ID_QUERY_RESULT;
    '*[\n  _type == "order"\n] | order(createdAt desc) [0...$limit] {\n  _id,\n  orderNumber,\n  email,\n  total,\n  status,\n  createdAt\n}': RECENT_ORDERS_QUERY_RESULT;
    '*[\n  _type == "order"\n  && stripePaymentId == $stripePaymentId\n][0]{ _id }': ORDER_BY_STRIPE_PAYMENT_ID_QUERY_RESULT;
    '*[\n  _type == "product"\n] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': ALL_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && featured == true\n  && stock > 0\n] | order(name asc) [0...6] {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FEATURED_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && defined(images)\n  && count(images) > 0\n  && stock > 0\n] | order(_createdAt desc) [0...14] {\n  _id,\n  name,\n  "slug": slug.current,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': GALLERY_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock > 0\n] | order(stock asc, name asc) [0...8] {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': BEST_SELLERS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && category->slug.current == $categorySlug\n] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock\n}': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '*[\n  _type == "product"\n  && slug.current == $slug\n][0] {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  salePrice,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  variantGroup,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "product"\n  && variantGroup == $variantGroup\n  && defined(variantGroup)\n  && variantGroup != ""\n] | order(name asc) {\n  _id,\n  "slug": slug.current,\n  color,\n  "image": images[0]{\n    asset->{\n      url\n    }\n  }\n}': VARIANT_SIBLINGS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && variantGroup == $variantGroup\n  && defined(variantGroup)\n  && variantGroup != ""\n] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  salePrice,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': VARIANT_SIBLINGS_FULL_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (\n    name match $searchQuery + "*"\n    || description match $searchQuery + "*"\n  )\n] | score(\n  boost(name match $searchQuery + "*", 3),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc) {\n  _id,\n  _score,\n  name,\n  "slug": slug.current,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock\n}': SEARCH_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_NAME_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(name desc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_NAME_DESC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(_createdAt desc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_NEWEST_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(price asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(price desc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(stock asc, name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_BEST_SELLING_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categorySlugs) == 0 || ("sale" in $categorySlugs && defined(salePrice)) || ("new" in $categorySlugs && isNew == true) || category->slug.current in $categorySlugs)\n  && (count($productTypes) == 0 || productType in $productTypes)\n  && (count($colors) == 0 || color in $colors)\n  && (count($materials) == 0 || material in $materials)\n  && ($minPrice == 0 || coalesce(salePrice, price) >= $minPrice)\n  && ($maxPrice == 0 || coalesce(salePrice, price) <= $maxPrice)\n  && ($searchQuery == "" || name match $searchQuery + "*" || description match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | score(\n  boost(name match $searchQuery + "*", 3),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc, name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT;
    '*[\n  _type == "product"\n  && _id in $ids\n] {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  stock\n}': PRODUCTS_BY_IDS_QUERY_RESULT;
    '*[_type == "product" && _id in $ids] {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': PRODUCTS_BY_IDS_FULL_QUERY_RESULT;
    '*[_type == "product" && stock > 0 && defined(images) && count(images) > 0] | order(featured desc, stock asc, _createdAt desc) [0...8] {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': POPULAR_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock > 0\n  && stock <= 5\n] | order(stock asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  stock,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': LOW_STOCK_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && category->slug.current == $categorySlug\n  && slug.current != $currentSlug\n  && stock > 0\n] | order(name asc) [0...4] {\n  _id,\n  name,\n  "slug": slug.current,\n  price,\n  salePrice,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  stock,\n  isNew,\n  variantGroup\n}': RELATED_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock == 0\n] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': OUT_OF_STOCK_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (\n    $searchQuery == ""\n    || name match $searchQuery + "*"\n    || description match $searchQuery + "*"\n    || category->title match $searchQuery + "*"\n  )\n  && ($categorySlug == "" || category->slug.current == $categorySlug)\n  && ($material == "" || material == $material)\n  && ($color == "" || color == $color)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n] | order(name asc) [0...20] {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': AI_SEARCH_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "searchQuery"\n] | order(count desc) [0...8] {\n  _id,\n  query,\n  count\n}': POPULAR_SEARCHES_QUERY_RESULT;
    '*[\n  _type == "searchQuery"\n  && query == $searchText\n][0] {\n  _id,\n  query,\n  count\n}': SEARCH_QUERY_BY_TEXT_QUERY_RESULT;
    'count(*[_type == "product"])': PRODUCT_COUNT_QUERY_RESULT;
    'count(*[_type == "order"])': ORDER_COUNT_QUERY_RESULT;
    'math::sum(*[\n  _type == "order"\n  && status in ["paid", "shipped", "delivered"]\n].total)': TOTAL_REVENUE_QUERY_RESULT;
    '*[\n  _type == "order"\n  && createdAt >= $startDate\n  && !(_id in path("drafts.**"))\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  "itemCount": count(items),\n  items[]{\n    quantity,\n    priceAtPurchase,\n    "productName": product->name,\n    "productId": product->_id\n  }\n}': ORDERS_LAST_7_DAYS_QUERY_RESULT;
    '{\n  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),\n  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),\n  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),\n  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])\n}': ORDER_STATUS_DISTRIBUTION_QUERY_RESULT;
    '*[\n  _type == "order"\n  && status in ["paid", "shipped", "delivered"]\n  && !(_id in path("drafts.**"))\n] {\n  items[]{\n    "productId": product->_id,\n    "productName": product->name,\n    "productPrice": product->price,\n    quantity\n  }\n}.items[]': TOP_SELLING_PRODUCTS_QUERY_RESULT;
    '*[_type == "product"] {\n  _id,\n  name,\n  price,\n  stock,\n  "category": category->title\n}': PRODUCTS_INVENTORY_QUERY_RESULT;
    '*[\n  _type == "order"\n  && status == "paid"\n  && !(_id in path("drafts.**"))\n] | order(createdAt asc) {\n  _id,\n  orderNumber,\n  total,\n  createdAt,\n  email,\n  "itemCount": count(items)\n}': UNFULFILLED_ORDERS_QUERY_RESULT;
    '{\n  "currentPeriod": math::sum(*[\n    _type == "order"\n    && status in ["paid", "shipped", "delivered"]\n    && createdAt >= $currentStart\n    && !(_id in path("drafts.**"))\n  ].total),\n  "previousPeriod": math::sum(*[\n    _type == "order"\n    && status in ["paid", "shipped", "delivered"]\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path("drafts.**"))\n  ].total),\n  "currentOrderCount": count(*[\n    _type == "order"\n    && createdAt >= $currentStart\n    && !(_id in path("drafts.**"))\n  ]),\n  "previousOrderCount": count(*[\n    _type == "order"\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path("drafts.**"))\n  ])\n}': REVENUE_BY_PERIOD_QUERY_RESULT;
  }
}
